inherit: true

filter:
  paths: [src/*, tests/*]

checks:
  php:
    code_rating: true
    duplication: true

build:
  dependencies:
    override:
      - true
  tests:
    override:
      - phpcs-run