language: php
php:
 - 7.1

env:
  - DB=MYSQL CORE_RELEASE=4

before_script:
 - phpenv rehash
 - composer self-update
 - git clone git://github.com/silverstripe/silverstripe-travis-support.git ~/travis-support
 - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
 - cd ~/builds/ss

script:
 - vendor/bin/phpunit --coverage-clover=coverage.xml silverstripe-oauth2-server/tests

after_success:
  - mv coverage.xml ~/build/$TRAVIS_REPO_SLUG
  - cd ~/build/$TRAVIS_REPO_SLUG
  - bash <(curl -s https://codecov.io/bash)