language: php
php:
 - 7.1

env:
  - DB=MYSQL CORE_RELEASE=4

before_script:
 - phpenv rehash
 - echo 'memory_limit = 2048M' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
 - composer self-update
 - composer validate
 - composer install --prefer-dist --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose --profile

script:
 - vendor/bin/phpunit --coverage-clover=coverage.xml ./tests

after_success:
  - mv coverage.xml ~/build/$TRAVIS_REPO_SLUG
  - cd ~/build/$TRAVIS_REPO_SLUG
  - bash <(curl -s https://codecov.io/bash)