language: php
php:
 - 7.1

env:
  - DB=MYSQL CORE_RELEASE=4

before_script:
 - phpenv rehash
 - composer self-update

script:
 - vendor/bin/phpunit --coverage-clover=coverage.xml ./tests

after_success:
  - mv coverage.xml ~/build/$TRAVIS_REPO_SLUG
  - cd ~/build/$TRAVIS_REPO_SLUG
  - bash <(curl -s https://codecov.io/bash)