SilverStripe\Control\Director:
  rules:
    'oauth2/authorise': 'AdvancedLearning\Oauth2Server\Controllers\AuthoriseController'

Silverstripe\Core\Injector\Injector:
  AdvancedLearning\Oauth2Server\Services\Authenticator:
    class: AdvancedLearning\Oauth2Server\Services\AuthenticationService

  AdvancedLearning\Oauth2Server\AuthorizationServer\Generator:
    class: AdvancedLearning\Oauth2Server\AuthorizationServer\DefaultGenerator

  AdvancedLearning\Oauth2Server\Controllers\AuthoriseController:
    constructor:
      0: '%$AdvancedLearning\Oauth2Server\AuthorizationServer\Generator'